# center: x,y  size: x,y   yaw
map_box:              [ 2,      2,     2,    2,   2,
                        0,     -1,     1,    1,   2,
                       -4,   -2.5,   0.5,  4.1,   0,
                     -3.8,    2.5,   0.1,  4.1,   0,
                     -3.8,   -0.0,  0.05,    1,   0,
                     -2.8,    4.7,   2.0, 0.10, 0.0,
                       ]

# map_size  xmin xmax ymin ymax
map_size:             [-10,  10,  -10,  10]


# # center: x,y  size: x,y   yaw
# map_box:              [-4,   0,   6,0.5,   0,
#                        -4,  -6,   6,0.5,   0,
#                        -1,  -1, 0.5,  2,   0,
#                        -1,  -5, 0.5,  2,   0,
#                        -7,  -3, 0.5,  6,   0,
#                        ]

# # map_size  xmin xmax ymin ymax zmin zmax
# map_size:             [-9,  9,  -9,  7]