# center: x,y  size: x,y   yaw
map_box:              [  
                        # 0.5, -6.8, 19, 0.35, 0,
                         0.5, -6.8, 21, 0.35, 0,
                        -8.5, -9, 0.95, 2, 0,
                        -6.5, -8, 0.95, 2, 0,
                        -8.5, -9, 0.95, 2, 0,
                        -6.5, -8, 0.95, 2, 0,
                        -4.5, -9, 0.95, 2, 0,
                        -2.5, -8, 0.95, 2, 0,
                        # -0.5, -9, 0.95, 2, 0,
                        -0.5, -8.5, 1.45, 0.45, 0,
                         1.5, -8, 0.95, 2, 0,
                         3.5, -9, 0.95, 2, 0,
                         5.5, -8, 0.95, 2, 0,
                         7.5, -9, 0.95, 2, 0,

                        #  0.5, -2.4, 19, 0.35, 0,
                           0, -1.9, 20, 0.35, 0,
                        
                        -8.7, -5.1, 0.45, 3.1, 0,
                        -7.9, -3.8, 1.05, 0.45, 0,
                        -7.2, -4.0, 0.35, 0.15, 0,

                        -5.2, -3.9, 0.95, 3.65, 0,
                        -6.2, -5.0, 1.35, 0.45, 0,
                        -7.1, -5.2, 1.35, 0.15, 0,
                        -7.5, -5.5, 0.15, 0.65, 0,


                        -3.3, -5.1, 0.95, 3.1, 0,
                        -2.3, -3.7, 1.05, 0.45, 0,
                        -0.3, -3.7, 0.95, 3.1, 0,
                        -1.3, -5.2, 0.95, 0.15, 0,
                        
                        -1.4, -6.3, 0.35, 0.55, 0,
                         
                         1.5, -5.1, 0.95, 3.3, 0,
                         2.5, -3.6, 0.95, 0.45, 0,
                         
                         4.5, -3.6, 0.95, 2.9, 0,
                         3.6, -5.0, 0.95, 0.15, 0,
                         3.4, -5.4, 0.45, 0.8, 0,

                         6.5, -5.0, 3.15, 0.15, 0,
                         8.0, -4.0, 0.15, 1.95, 0,
                         7.1, -3.0, 1.95, 0.15, 0,
                         6.1, -3.4, 0.15, 0.95, 0,


                        #  6.5, -5.1, 0.95, 3.3, 0,
                        #  7.5, -3.8, 0.95, 0.45, 0,
                        #  9.5, -4.1, 0.95, 3, 0,
                        #  8.6, -5.3, 0.95, 0.45, 0,



                        # -8.7, -2.8, 0.15, 0.45, 0,
                        -8.5, -3.5, 0.15, 0.85, 0,
                        -3.4, -3.5, 0.15, 1.15, 0,

                      ]

# map_size  xmin xmax ymin ymax
map_size:             [-10,  10,  -10,  10]


# # center: x,y  size: x,y   yaw
# map_box:              [-4,   0,   6,0.5,   0,
#                        -4,  -6,   6,0.5,   0,
#                        -1,  -1, 0.5,  2,   0,
#                        -1,  -5, 0.5,  2,   0,
#                        -7,  -3, 0.5,  6,   0,
#                        ]

# # map_size  xmin xmax ymin ymax zmin zmax
# map_size:             [-9,  9,  -9,  7]