# center: x,y  size: x,y   yaw
map_box:              [  0, -5.8, 20, 0.35, 0,
                        -8.8, -8.5, 0.35, 3, 0, 
                        -8, -7.2, 2, 0.35, 0, 
                        -7.2, -8.5, 0.35, 3, 0,

                        -5.8, -7.3, 0.35, 3, 0, 
                        -5, -8.8, 2, 0.35, 0, 
                        -4.2, -7.3, 0.35, 3, 0,

                        -2.8, -8.5, 0.35, 3, 0, 
                        -2, -7.2, 2, 0.35, 0, 
                        -1.2, -8.5, 0.35, 3, 0,

                        0.2, -7.3, 0.35, 3, 0, 
                        1, -8.8, 2, 0.35, 0, 
                        1.8, -7.3, 0.35, 3, 0,


                        3.2, -8.5, 0.35, 3, 0, 
                        4, -7.2, 2, 0.35, 0, 
                        4.8, -8.5, 0.35, 3, 0,

                        6.2, -7.3, 0.35, 3, 0, 
                        7, -8.8, 2, 0.35, 0, 
                        7.8, -7.3, 0.35, 3, 0,

                        8.5, -8.9, 1.0, 0.15, 0,
                        9.0, -8.0, 0.15, 2.0, 0,

                       ]

# map_size  xmin xmax ymin ymax
map_size:             [-10,  10,  -10,  10]


# # center: x,y  size: x,y   yaw
# map_box:              [-4,   0,   6,0.5,   0,
#                        -4,  -6,   6,0.5,   0,
#                        -1,  -1, 0.5,  2,   0,
#                        -1,  -5, 0.5,  2,   0,
#                        -7,  -3, 0.5,  6,   0,
#                        ]

# # map_size  xmin xmax ymin ymax zmin zmax
# map_size:             [-9,  9,  -9,  7]