# center: x,y  size: x,y   yaw
map_box:              [  
                        -6, 1, 0.1, 6, 0,
                        -2, -4, 0.1, 10, 0,
                        6, 1, 0.1, 6, 0,
                        0.5, 1, 5, 0.1, 0,
                        3.5, -2, 5, 0.1, 0,
                        0, 4, 20, 0.5, 0,
                        0, -5, 20, 0.5, 0,
                      ]

# map_size  xmin xmax ymin ymax
map_size:             [-10,  10,  -10,  10]
